package com.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-16T21:16:54.300-02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "HelloImplService", 
                  wsdlLocation = "http://localhost:8081/ws/services/Hello?wsdl",
                  targetNamespace = "http://service.ws.com/") 
public class HelloImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.com/", "HelloImplService");
    public final static QName HelloPort = new QName("http://service.ws.com/", "HelloPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/ws/services/Hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/ws/services/Hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort() {
        return super.getPort(HelloPort, Hello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, Hello.class, features);
    }

}
