package com.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-16T21:16:54.290-02:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://service.ws.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.ws.com/", className = "com.ws.client.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.ws.com/", className = "com.ws.client.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
